package com.islandempires.resourcesservice.enums;

public enum IslandResourceEnum {
    WOOD,
    WOOD_HOURLY_PRODUCTION,
    IRON,
    IRON_HOURLY_PRODUCTION,
    IRON_HOURL_PRODUCTION_MULTIPLY,
    CLAY,
    CLAY_HOURLY_PRODUCTION,
    CLAY_HOURL_PRODUCTION_MULTIPLY,
    RAW_MATERIAL_STORAGE_SIZE,
    GOLD,
    MEAT_HOURLY_PRODUCTION,
    FISH_HOURLY_PRODUCTION,
    WHEAT_HOURLY_PRODUCTION,
    ADDITIONAL_HAPPINESS_SCORE,
    POPULATION,
    TEMPORARY_POPULATION
}
