server:
  host: 192.168.0.14
  port: 500

spring:
  application:
    name: map-service
  data:
    elasticsearch:
      connectTimeout: 10000
      connectionRequestTimeout: 10000
      socketTimeout: 10000
      maxRetryTimeoutMillis: 60000
      repositories:
        enabled: true
      client:
        reactive:
          endpoints: localhost:9200
  main:
    allow-bean-definition-overriding: true

urls:
  gateway: http://localhost:9001


