server:
  host: localhost
  port: ${PORT:1000}

spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: localhost
  server:
    leaseRenewalThresholdUpdateIntervalMs: 60000
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
