server:
  host: 192.168.0.14
  port: ${PORT:1000}

spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: 192.168.0.14
  server:
    leaseRenewalThresholdUpdateIntervalMs: 60000
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
