package com.islandempires.buildingworker.enums;

public enum IslandResourceEnum {
    WOOD,
    WOOD_HOURLY_PRODUCTION,
    IRON,
    IRON_HOURLY_PRODUCTION,
    CLAY,
    CLAY_HOURLY_PRODUCTION,
    RAW_MATERIAL_STORAGE_SIZE,
    GOLD,
    MEAT_HOURLY_PRODUCTION,
    FISH_HOURLY_PRODUCTION,
    WHEAT_HOURLY_PRODUCTION,
    ADDITIONAL_HAPPINESS_SCORE,
    POPULATION,
    TEMPORARY_POPULATION
}
