spring:
  application:
    name: resources-websocket-service
  data:
    mongodb:
        host: localhost
        username: user
        database: resources
        port: 27017
    data:
      mongodb:
        connection-pool:
          max-size: 1000
          min-size: 20
          max-wait-time: 5000

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:1000/eureka/

urls:
  gateway: http://localhost:9000

