server:
  host: localhost
  port: 3003

spring:
  application:
    name: resources-websocket-service
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: web-socket-groupp
      resource-sender-topic: island-resource-stream
      clan-stream: clan-stream
      clan-user-change-topic: clan-user-change-topic
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  data:
    mongodb:
        host: localhost
        username: user
        database: session
        port: 28000
    data:
      mongodb:
        connection-pool:
          max-size: 1000
          min-size: 20
          max-wait-time: 5000

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:1000/eureka/

urls:
  gateway: http://localhost:9001
