server:
  host: 192.168.0.14
  port: 9000

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: api-gateway
  config:
    import: "optional:configserver:"
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      routes:
        - id: resource-service
          uri: http://localhost:2000
          predicates:
            - Path=/resource/public/**
        - id: auth-service
          uri: http://localhost:1001
          predicates:
            - Path=/auth/**
        - id: game-service
          uri: http://localhost:2002
          predicates:
            - Path=/gameservice/public/**
        - id: island-service
          uri: http://localhost:3000
          predicates:
            - Path=/island/public/**
        - id: building-service
          uri: http://localhost:4000
          predicates:
            - Path=/building/public/**
        - id: military-service
          uri: http://localhost:6000
          predicates:
            - Path=/military/public/**
        - id: map-service
          uri: http://localhost:500
          predicates:
            - Path=/map/public/**
        - id: clan-service
          uri: http://localhost:2050
          predicates:
            - Path=/clan/public/**
        - id: websocket-service
          uri: http://localhost:3003
          predicates:
            - Path=/websocket/**

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:1000/eureka/


logging:
  level:
    org.springframework.cloud.gateway: DEBUG