server:
  host: 192.168.0.14
  port: 9000

spring:
  application:
    name: api-gateway
  main:
    allow-bean-definition-overriding: true

gateway:
  auth: http://192.168.0.14:1000
  resource: http://192.168.0.14:2000


eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://192.168.0.14:1000/eureka/


logging:
  level:
    org.springframework.cloud.gateway: DEBUG


auth-service-url: http://192.168.0.14:1000