server:
  host: localhost
  port: 9001

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: api-gateway-private
  config:
    import: "optional:configserver:"
  cloud:
    gateway:
      routes:
        - id: resource-service
          uri: http://localhost:2000
          predicates:
            - Path=/resource/private/**
        - id: auth-service
          uri: http://localhost:1001
          predicates:
            - Path=/auth/**
        - id: auth-service
          uri: http://localhost:1001
          predicates:
            - Path=/private/auth/**
        - id: game-service
          uri: http://localhost:2002
          predicates:
            - Path=/gameservice/private/**
        - id: island-service
          uri: http://localhost:3000
          predicates:
            - Path=/island/private/**
        - id: building-service
          uri: http://localhost:4000
          predicates:
            - Path=/building/private/**
        - id: military-service
          uri: http://localhost:6000
          predicates:
            - Path=/military/private/**

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:1000/eureka/


logging:
  level:
    org.springframework.cloud.gateway: DEBUG