server:
  host: 192.168.0.14
  port: 2000

spring:
  application:
    name: resources-service
  data:
    mongodb:
      host: 192.168.0.14
      username: user
      database: resources
      port: 27017
    data:
      mongodb:
        connection-pool:
          max-size: 1000
          min-size: 20
          max-wait-time: 5000
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: island-resources-id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      island-delete-topic: island-delete-topic

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://192.168.0.14:1000/eureka/

urls:
  gateway: http://192.168.0.14:9000

