server:
  host: 192.168.0.14
  port: 2000

spring:
  application:
    name: resources-service
  data:
    mongodb:
      host: 192.168.0.14
      username: user
      database: resources
      port: 27017

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://192.168.0.14:1000/eureka/
