server:
  host: 192.168.0.14
  port: 6000

spring:
  application:
    name: military-service
  datasource:
    url: jdbc:mariadb://localhost:3308/military
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
    testWhileIdle: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
    hibernate:
      ddl-auto: update
      format_sql: true

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://192.168.0.14:1000/eureka/

urls:
  gateway: http://192.168.0.14:9000

