server:
  host: 192.168.0.14
  port: 2002

spring:
  application:
    name: game-service
  data:
    mongodb:
      host: 192.168.0.14
      username: user
      database: gameserver
      port: 27012

urls:
  island: 192.168.0.14:3000
  island-resource: 192.168.0.14:2000