server:
  host: 192.168.0.14
  port: 2002
  tomcat:
    max-connections: 500
    max-threads: 500
  connection-timeout: 60000

spring:
  application:
    name: game-service
  data:
    mongodb:
      host: 192.168.0.14
      username: user
      database: gameserver
      port: 27012
  kafka:
    consumer:
      island-delete-topic-status: island-delete-topic-status
      group-id: group-id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      island-delete-topic: island-delete-topic


urls:
  island: 192.168.0.14:3000
  island-resource: 192.168.0.14:2000
  island-building: 192.168.0.14:4000
  gateway: http://192.168.0.14:9000

