server:
  host: localhost
  port: 4000
  tomcat:
    max-connections: 2000
    max-threads: 100
  connection-timeout: 60000

spring:
  application:
    name: building-service
  data:
    mongodb:
      host: localhost
      username: user
      database: building
      port: 27400
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: island-building-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      island-delete-topic: island-delete-topic
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 5
          initial-interval: 1000
          max-interval: 10000
          multiplier: 2
          stateless: true

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:1000/eureka/

urls:
  gateway: http://localhost:9001


