package com.islandempires.islandservice.enums;

public enum IslandResourceEnum {
    WOOD,
    WOOD_HOURLY_PRODUCTION,

    IRON,
    IRON_HOURLY_PRODUCTION,

    CLAY,
    CLAY_HOURLY_PRODUCTION,

    GOLD,

    RAW_MATERIAL_STORAGE_SIZE,

    MEAT_FOOD_COEFFICIENT,
    MEAT_HOURLY_PRODUCTION,

    FISH_FOOD_COEFFICIENT,
    FISH_HOURLY_PRODUCTION,

    WHEAT_FOOD_COEFFICIENT,
    WHEAT_HOURLY_PRODUCTION,

    POPULATION,
    TEMPORARY_POPULATION,

    POPULATION_LIMIT,

    HAPPINESS_SCORE,
    ADDITIONAL_HAPPINESS_SCORE
}
