server:
  host: 192.168.0.14
  port: 2001

spring:
  application:
    name: resources-service
  datasource:
    url: jdbc:mysql://192.168.0.14:3306/server
    username: root
    password: 1234
    testWhileIdle: true

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://192.168.0.14:1000/eureka/
