server:
  host: localhost
  port: 2001

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: resourceworker
  data:
    mongodb:
      host: localhost
      username: user
      database: building
      port: 27400

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:1000/eureka/

debezium:
  connector:
    name: building-connector
    connectorClass: io.debezium.connector.mongodb.MongoDbConnector
    mongodb:
      host: mongodb://localhost:27400
      user: user
      database: building
  database:
    whitelist:
      - "building"
    collection:
      whitelist:
        - "building.BuildingScheduledTaskDone"
      excludeFieldList: ~
  kafka:
    topicPrefix: "mytopic"


urls:
  gateway: http://localhost:9000
