server:
  host: localhost
  port: 2050

spring:
  application:
    name: clan-service
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mariadb://localhost:3310/clan
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
    testWhileIdle: true
  config:
    import: "optional:configserver:"

  jpa:
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
    hibernate:
      ddl-auto: update
      format_sql: true
      cache:
        use_second_level_cache: false
        use_query_cache: false

  kafka:
    producer:
      clan-change-topic: clan-change-topic
      clan-delete-topic: clan-delete-topic
      clan-user-change-topic: clan-user-change-topic
    consumer:
      bootstrap-servers: localhost:9092
      group-id: clan-id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      server-user-delete-topic: server-user-delete-topic
    json:
      value:
        default:
          type: com.example.YourEventClass
      trusted:
        packages: "*"

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 5
          initial-interval: 1000
          max-interval: 10000
          multiplier: 2
          stateless: true


eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:1000/eureka/

urls:
  gateway: http://localhost:9001


