server:
  host: 192.168.0.14
  port: 3000

spring:
  application:
    name: island-service
  data:
    mongodb:
      host: 192.168.0.14
      username: user
      database: island
      port: 27300
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: island-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      island-delete-topic: island-delete-topic
    producer:
      island-delete-topic-status: island-delete-topic-status
      island-request-topic: island-request-topic

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://192.168.0.14:1000/eureka/

urls:
  gateway: http://192.168.0.14:9000
