server:
  host: localhost
  port: 3000

spring:
  application:
    name: island-service
  data:
    mongodb:
      host: localhost
      username: user
      database: island
      port: 27300
  config:
    import: "optional:configserver:"
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: island-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      island-delete-topic: island-delete-topic
    producer:
      island-delete-topic-status: island-delete-topic-status
      island-delete-topic: island-delete-topic
      server-user-delete-topic: server-user-delete-topic

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:1000/eureka/

urls:
  gateway: http://localhost:9001
