server:
  host: 192.168.0.14
  port: 3000

spring:
  application:
    name: island-service
  data:
    mongodb:
      host: 192.168.0.14
      username: user
      database: island
      port: 27300

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://192.168.0.14:1000/eureka/