server:
  host: 192.168.0.14
  port: 9000

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: resource-service
          uri: http://192.168.0.14:2000
          predicates:
            - Path=/resource/**
        - id: auth-service
          uri: http://192.168.0.14:1001
          predicates:
            - Path=/auth/**
        - id: game-service
          uri: http://192.168.0.14:2002
          predicates:
            - Path=/gameservice/**
        - id: island-service
          uri: http://192.168.0.14:3000
          predicates:
            - Path=/island/**
        - id: building-service
          uri: http://192.168.0.14:4000
          predicates:
            - Path=/building/**
        - id: military-service
          uri: http://192.168.0.14:6000
          predicates:
            - Path=/military/**

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://192.168.0.14:1000/eureka/


logging:
  level:
    org.springframework.cloud.gateway: DEBUG