server:
  host: localhost
  port: 3002

spring:
  application:
    name: resourceworker
  data:
    mongodb:
      host: localhost
      username: user
      database: resources
      port: 27017

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:1000/eureka/
